### ISSUE TITLE
后台提示红色信息 

### ISSUE THREAD

**Issue by TaiChi01** [GamerNoTitle/MCDR-Waypoints#4]
服务器winsever
MCDRV1.3
MC版本1.16.5
Error invoking listener EventListener[plugin=waypoints@0.0.0,priority=1000,callback=<function on_info at 0x0000021F94109550>]
Traceback (most recent call last):
  File "E:\MCDRShip\mcdreforged\plugin\plugin_manager.py", line 447, in trigger_listener
    listener.execute(self.mcdr_server.server_interface, *args)
  File "E:\MCDRShip\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "plugins\Waypoints.py", line 255, in on_info
    add(server,info,message)
  File "plugins\Waypoints.py", line 80, in add
    pos,Dimension=get_pos(server,info)
  File "plugins\Waypoints.py", line 228, in get_pos
    pos=PlayerInfoAPI.getPlayerInfo(server, info.player, 'Pos')
AttributeError: 'NoneType' object has no attribute 'getPlayerInfo'

**Comment by TaiChi01** [comment]
是因为playerinfoapi不支持1.0+的MCDR，而这个插件需要playerinfo造成的吗
